### ISSUE TITLE
Invincibility suggestion!

### ISSUE THREAD

**Issue by TZ122** [SpaceNiklas/VillagerFixes#1]
Came from the lifesteal plugin but so glad I found this!

Not sure if this is the right spot for suggestions but possible to add an alias for invincibility such as /timer? and a lang file to change the text? (My server is not English based). Much thanks for making such a simple plugin

**Comment by SpaceNiklas** [comment]
Yes I can make that possible! Expect it to be done today or on Saturday! If you have any other suggestions (even for whole plugins) please tell me via Discord or here! :)

**Comment by TZ122** [comment]
Good to know! I look forward to the release gracias !

**Comment by SpaceNiklas** [comment]
All done you can download the latest release and it's all included! Just delete your current plugin folder and restart the server with the current plugin installed and you can edit the new config.yml to your liking. You can then test the plugin by deleting the logs folder, the playercache.json and in your world the playerdata folder! If you run into any problems or have suggestion just contact me here or on discord and I'll look into it! :)
